# Generated by Django 2.2.5 on 2020-09-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PepoleInfo',
            new_name='PeopleInfo',
        ),
    ]
